---
# Change - make 'xxx' unique across projects.
# See what is taken and add your chosen IP here:
# https://github.com/madewithlove/devops/blob/master/documentation/list_ipadresses_vagrant.md
ip: "192.168.xxx.xxx"

 # Change to your project name
projectname: "projectname"

ports:
    ssh: "56xxx"
    web: "8xxx"
    mysql: "33xxx"

# Set to true what you want to install on top of the base box
elasticsearch: false
mailcatcher: false
