---
# Set all these values to the same as skeletor-config.yaml when you bake an image
ip: "192.168.57.100"

 # change to your project name
projectname: "projectname"

ports:
    ssh: "56201"
    web: "8000"
    mysql: "33060"